services:
  douyin-api:
    image: evil0ctal/douyin_tiktok_download_api:latest
    container_name: douyin-api
    ports:
      - "8081:80"
    restart: unless-stopped
    volumes:
      - ./config/douyin_web_config.yaml:/app/crawlers/douyin/web/config.yaml:ro
