services:
  douyin-api:
    image: evil0ctal/douyin_tiktok_download_api:latest
    container_name: douyin-api
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ./config/douyin_cookie.txt:/app/cookie.txt:ro
